export enum ConfigurationSettingsType {
	GWP = "GWP",
	PROJECTIONS_WITH_MEASURES = "PROJECTIONS_WITH_MEASURES",
	PROJECTIONS_WITH_ADDITIONAL_MEASURES = "PROJECTIONS_WITH_ADDITIONAL_MEASURES",
	PROJECTIONS_WITHOUT_MEASURES = "PROJECTIONS_WITHOUT_MEASURES",
}
