export enum NatImplementor {
  AGRDEPT = "Agriculture Department",
  CLMDEPT = "Climate Change Department",
  CIVAVIPM = "Department of Civil Aviation, Ports and Marine",
  DEPENER = "Department of Energy",
  LANDTRAN = "Department of Land Transport",
  ENVDEPT = "Environment Department",
  LANDTRAAG = "Land Transport Agency",
  MARSAF = "Maritime Safety Authority",
  PUBTRANSCOR = "Public Transport Corporation",
  REVENCOM = "Revenue Commission",
  TOURBOARD = "Tourism Board",
  MININVEST = "Minister for Investment, Entrepreneurship and Industry",
  MINFORAFF = "Minister of Foreign Affairs and Tourism",
  MINHEALTH = "Ministry of Health",
  MININTAFF = "Ministry of Internal Affairs",
  MINTRAN = "Ministry of Transport",
  MINLOCGOV = "Ministry for Local Government and Community Affairs",
  MINAGRICLIMENV = "Ministry of Agriculture, Climate Change and Environment",
  MINEDU = "Ministry of Education",
  MINEMPSSAFF = "Ministry of Employment and Social Affairs",
  MINFIN = "Ministry of Finance, Economic Planning & Trade",
  MINFISH = "Ministry of Fisheries",
  MINLANDHOU = "Ministry of Lands and Housing",
  MINYOUTHSPOFAM = "Ministry of Youth, Sports and Family",
  OFFPRES = "Office of the President",
}

export enum IntImplementor {
  AFC = "AFC",
  AFD = "AFD",
  AFDB = "AFDB",
  EBRD = "EBRD",
  EIB = "EIB",
  FAO = "FAO",
  GIZ = "GIZ",
  IMF = "IMF",
  IMO = "IMO",
  IUCN = "IUCN",
  NEFCO = "NEFCO",
  UNWO = "UN Women",
  UNDP = "UNDP",
  UNEP = "UNEP",
  UNESCO = "UNESCO",
  UNFCCC = "UNFCCC",
  UNFPA = "UNFPA",
  UNICEF = "UNICEF",
  UNIDO = "UNIDO",
  USAID = "USAID",
  WFP = "WFP",
  WMO = "WMO",
  WB = "World Bank",
}

export enum Recipient {
  MININVEST = "Minister for Investment, Entrepreneurship and Industry",
  MINFORAFF = "Minister of Foreign Affairs and Tourism",
  MINHEALTH = "Ministry of Health",
  MININTAFF = "Ministry of Internal Affairs",
  MINTRAN = "Ministry of Transport",
  MINLOCGOV = "Ministry for Local Government and Community Affairs",
  MINAGRICLIMENV = "Ministry of Agriculture, Climate Change and Environment",
  MINEDU = "Ministry of Education",
  MINEMPSSAFF = "Ministry of Employment and Social Affairs",
  MINFIN = "Ministry of Finance, Economic Planning & Trade",
  MINFISH = "Ministry of Fisheries",
  MINLANDHOU = "Ministry of Lands and Housing",
  MINYOUTHSPOFAM = "Ministry of Youth, Sports and Family",
  OFFPRES = "Office of the President",
}

export enum EntityType {
  ACTION = "action",
  PROGRAM = "program",
  PROJECT = "project",
  ACTIVITY = "activity",
}

export enum GHGS {
  CO = "CO2",
  CH = "CH4",
  NO = "N2O",
  HFC = "HFCs",
  NF = "NF3",
  PFC = "PFCs",
  SF = "SF6",
}

export enum OrgType {
  GOVERNMENT = "Government",
  DEPARTMENT = "Department",
  API = "API",
}

export enum Sector {
  Energy = "Energy",
  Transport = "Transport",
  Industry = "Industry (IPPU)",
  Agriculture = "Agriculture",
  Forestry = "Forestry",
  WaterAndSanitation = "Water and Sanitation",
  LandUse = "Land Use",
  CrossCutting = "Cross-cutting",
  Other = "Other",
}

export enum SubSector {
  GRID = "Grid-Connected Generation (electricity)",
  OFFGRID = "Off-Grid / Rural Generation (electricity)",
  TND = "Transmission & Distribution (electricity)",
  FUEL = "Fuels",
  GOV = "Government",
  IND = "Industry",
  APPL = "Appliances",
  WATER = "Water",
  CITY = "Cities",
  BUILDING = "Buildings",
  LAND = "Land (transport)",
  MARITIME = "Maritime (transport)",
  AVIATION = "Aviation (transport)",
  WASTEW = "Wastewater",
  WASTES = "Solid Waste",
  FOREST = "Forestry",
  AGFOREST = "Agroforestry",
  AGRC = "Agriculture",
  LANDUSE = "Land Use",
  COASTAL = "Coastal",
  FISHING = "Fishing",
  BIOD = "Biodiversity",
  ECOS = "Ecosystems",
  NBS = "Nature Based Solutions",
  TOURISM = "Tourism",
  COMM = "Commercial",
  HOUSE = "Households",
  MULTISUB = "Multi-Subsector",
  NA = "Not Applicable",
}

export enum Role {
  SADMIN = "Super Admin",
  ADMIN = "Admin",
  OBSERVER = "Observer",
  USER = "User",
}
