export enum MitigationTypes {
  Agriculture,
  Solar,
  BiomassEnergy,
  CCS,
  Cement,
  CoalBedMineMethane,
  EEHouseholds,
  EEIndustry,
  EEOwnGeneration,
  EEService,
  EESupplySide,
  EnergyDistribution,
  Forestry,
  FossilFuelSwitch,
  Fugitive,
  Geothermal,
  HFCsPFCsSF6,
  Hydro,
  Landfills,
  Marine,
  MethaneAvoidance,
  N2O,
  Transport,
  Wind,
}

export const mitigationTypeList = [
  { value: MitigationTypes.Agriculture.valueOf(), label: 'Agriculture' },
  { value: MitigationTypes.Solar.valueOf(), label: 'Solar' },
  { value: MitigationTypes.BiomassEnergy.valueOf(), label: 'Biomass energy', disabled: true },
  { value: MitigationTypes.CCS.valueOf(), label: 'CCS', disabled: true },
  { value: MitigationTypes.Cement.valueOf(), label: 'Cement', disabled: true },
  {
    value: MitigationTypes.CoalBedMineMethane.valueOf(),
    label: 'Coal bed/mine methane',
    disabled: true,
  },
  { value: MitigationTypes.EEHouseholds.valueOf(), label: 'EE households', disabled: true },
  { value: MitigationTypes.EEIndustry.valueOf(), label: 'EE industry', disabled: true },
  { value: MitigationTypes.EEOwnGeneration.valueOf(), label: 'EE own generation', disabled: true },
  { value: MitigationTypes.EEService.valueOf(), label: 'EE service', disabled: true },
  { value: MitigationTypes.EESupplySide.valueOf(), label: 'EE supply side', disabled: true },
  {
    value: MitigationTypes.EnergyDistribution.valueOf(),
    label: 'Energy distribution',
    disabled: true,
  },
  { value: MitigationTypes.Forestry.valueOf(), label: 'Forestry', disabled: true },
  {
    value: MitigationTypes.FossilFuelSwitch.valueOf(),
    label: 'Fossil fuel switch',
    disabled: true,
  },
  { value: MitigationTypes.Fugitive.valueOf(), label: 'Fugitive', disabled: true },
  { value: MitigationTypes.Geothermal.valueOf(), label: 'Geothermal', disabled: true },
  { value: MitigationTypes.HFCsPFCsSF6.valueOf(), label: 'HFCs, PFCs, SF6', disabled: true },
  { value: MitigationTypes.Hydro.valueOf(), label: 'Hydro', disabled: true },
  { value: MitigationTypes.Landfills.valueOf(), label: 'Landfills', disabled: true },
  { value: MitigationTypes.Marine.valueOf(), label: 'Marine', disabled: true },
  { value: MitigationTypes.MethaneAvoidance.valueOf(), label: 'Methane avoidance', disabled: true },
  { value: MitigationTypes.N2O.valueOf(), label: 'N2O', disabled: true },
  { value: MitigationTypes.Transport.valueOf(), label: 'Transport', disabled: true },
  { value: MitigationTypes.Wind.valueOf(), label: 'Wind', disabled: true },
];
