export enum SectoralScope {
  EnergyIndustries = '1',
  EnergyDistribution = '2',
  EnergyDemand = '3',
  ManufacturingIndustries = '4',
  ChemicalIndustries = '5',
  Construction = '6',
  Transport = '7',
  MiningOrMineralProduction = '8',
  MetalProduction = '9',
  FugitiveEmissionsFromFuels = '10',
  FugitiveEmissionsFromProductionAndConsumptionOfHalocarbonsandSulphurHexafluoride = '11',
  SolventUse = '12',
  WasteHandlingAndDisposal = '13',
  AfforestationAndReforestation = '14',
  Agriculture = '15',
}
