export enum Organisation {
  AGRI_DEPT = 'Agriculture Department',
  CLIMATE_DEPT = 'Climate Change Department',
  CIVIL_AVIATION = 'Department of Civil Aviation, Ports and Marine',
  ENERGY_DEPT = 'Department of Energy',
  LAND_TRANS_DEPT = 'Department of Land Transport',
  ENV_DEPT = 'Environment Department',
  LAND_TRANS_AGENCY = 'Land Transport Agency',
  MARITIME_SAFETY = 'Maritime Safety Authority',
  PUB_TRANS_CORP = 'Public Transport Corporation',
  REVEN_COMM = 'Revenue Commission',
  TOUR_BOARD = 'Tourism Board',
  MIN_INV_ENP_IND = 'Minister for Investment, Entrepreneurship and Industry',
  Government = 'Government of Antarctica',
}
